Updates+fixes
VDR4Arch/vdr4arch pull request #229
Opened 2021-05-15 18:27 UTC by tmn505

Hi, here are some updates and fixes I spotted when rebuilding.

Aside from them I also saw Your topic on vdr-portal about restriction on Travis CI. I've hit that in January, but thought that I miss-configured something so shrugged it. In short I wanted some features which were only available on travis-ci.com, so switched from travis-ci.org and after few rebuilds it hit the limit. After some searching, I found out that they started restricting opensource repositories and if some wanted extended the limit they asked to send request. Looking on forums the requests seemed to be unanswered so it looked like they wanted to ditch most of CIs deployed on those repositories. Some people tie that to Travis bought two years ago by investing fund, I found it very plausible, but let's not delve in rumors. Anyway we have alternatives (unfortunately no native ARM machines) like GitHub Actions, Azure Pipelines or CircleCi. At least two of them GH Actions and Azure have good foundations and I don't think they'll go away anytime soon. I added Actions to my fork and it works very good. No additional setup except adding https://github.com/tmn505/vdr4arch/commit/ccb8b93086a62029ff928e19e13c4ba3863051a9. You can see the logs here: https://github.com/tmn505/vdr4arch/actions. It does not have caching enabled but the runs are allowed to be much longer than on Travis, so maybe even builds for ARM could be created.
If You're interested I can prepare a PR for x86_64 builds.

2021-05-16 09:17 UTC, M-Reimer requested changes

2021-05-16 09:17 UTC, M-Reimer commented on plugins/vdr-live/PKGBUILD
> +  git init --quiet && git apply --verbose "${srcdir}/8.patch"
Why this complex way of appending a patch.
Please replace with "patch -p1 -i ..."

2021-05-16 09:17 UTC, M-Reimer commented on plugins/vdr-live/PKGBUILD
> +        'https://patch-diff.githubusercontent.com/raw/MarkusEh/vdr-plugin-live/pull/8.patch'
This needs a proper name. "8.patch" could conflict with other PKGBUILDs if a global source directory is configured (which is on my build VM).

2021-05-16 09:17 UTC, M-Reimer commented on plugins/vdr-softhdcuvid/.SRCINFO
> +	source = vdr-plugin-softhdcuvid::git+https://github.com/jojo61/vdr-plugin-softhdcuvid#commit=2562c4eac535c890beffe9db86fd730da032cbd7
As proper releases are tagged, can you please use the tarballs from GitHub. Actually in future I want to put less effort into "output plugins" and would prefer to only follow upstream releases.

2021-05-16 09:17 UTC, M-Reimer commented on plugins/vdr-softhdcuvid/PKGBUILD
> +  make clean
Please not. I got the information from the upstream developer that the build() function should work as it was. If at all possible please don't build in "package..." functions.

2021-05-16 09:24 UTC, M-Reimer commented
> It does not have caching enabled but the runs are allowed to be much longer than on Travis, so maybe even builds for ARM could be created.

For sure won't work. I tried with qemu for way too long and I get random segmentation faults for no known reason so I finally gave up on this. To build on ARM it is required to have a native build host. I requested additional quote from TravisCI and got it. So in theory after applying your PR packages should be built.

TBH the ARM builds are currently my top priority as building on a Raspberry sucks. For x86_64 I do local builds anyway and as far as I know only I really uses the TravisCI builds. Not many Arch users with VDR left, I think.

2021-05-16 12:54 UTC, tmn505 commented on plugins/vdr-live/PKGBUILD
> +        'https://patch-diff.githubusercontent.com/raw/MarkusEh/vdr-plugin-live/pull/8.patch'
Ok, will do that.

2021-05-16 12:55 UTC, tmn505 commented on plugins/vdr-softhdcuvid/.SRCINFO
> +	source = vdr-plugin-softhdcuvid::git+https://github.com/jojo61/vdr-plugin-softhdcuvid#commit=2562c4eac535c890beffe9db86fd730da032cbd7
Ok, will do that. Next time I'll nag at upstream if a tag assignment is missing.

2021-05-16 13:23 UTC, tmn505 commented on plugins/vdr-softhdcuvid/PKGBUILD
> +  make clean
So let me explain what is occurring here. The problem is (maybe) not in upstream Makefile (it intends to build one type of plugin at a time) but in how we build the plugin. Keep in mind this line https://github.com/jojo61/vdr-plugin-softhdcuvid/blob/master/Makefile#L405.
In build() we do:
make CUVID=1
make clean
^^^ here we clean everything, even the plugin .so
make VAAPI=1
make clean
^^^ here we clean everything, even the plugin .so
make DRM=1
^^^ after this step we have only softhddrm plugin built with leftovers from the build.

In package():
for softhdcuvid:
make CUVID=1 DESTDIR="${pkgdir}" install
^^^ make detects change in flags and rebuilds, but does not recreate .dependencies file and all objects left from last make invocation in build()
for vaapi
make VAAPI=1 DESTDIR="${pkgdir}" install
^^^ make detects change in flags and rebuilds, but does not recreate .dependencies file and all objects left from last make invocation in build()
make DRM=1 DESTDIR="${pkgdir}" install
^^^ here we still have leftovers from build(), but as the last build was for drm all objects and .dependency file is correct

You can check result by simply installing vdr-softhdvaapi and running "vdr --help", You'll end up with same error as in these two messages:
https://www.vdr-portal.de/forum/index.php?thread/133957-cannot-get-softhdcuvid-to-start
https://www.vdr-portal.de/forum/index.php?thread/129888-softhdcuvid-with-hevc-and-uhd/&postID=1332886#post1332886

To fix this we should build each variant of this plugin separately. What's Your take on this?

2021-05-16 13:26 UTC, tmn505 commented on plugins/vdr-live/PKGBUILD
> +  git init --quiet && git apply --verbose "${srcdir}/8.patch"
"patch" doesn't handle git binary patches. There is small png file in that patch.

2021-05-16 13:38 UTC, tmn505 commented
> For sure won't work. I tried with qemu for way too long and I get random segmentation faults for no known reason so I finally gave up on this. To build on ARM it is required to have a native build host. I requested additional quote from TravisCI and got it. So in theory after applying your PR packages should be built.

That's nice that they answered Your request. Good to know that they didn't ditch free service. Yeah the build completed on the CI.

> 
> TBH the ARM builds are currently my top priority as building on a Raspberry sucks. For x86_64 I do local builds anyway and as far as I know only I really uses the TravisCI builds. Not many Arch users with VDR left, I think.

GH Action supports own builders but setting that probably would be some pain with little gain. For x86_64 I did setup repo on my own fork to build some additional modifications, so I only set up my repo in pacman.conf. Yeah probably not much people using even VDR as whole, most probably using it in LibreElec as backend.

2021-05-16 14:49 UTC, M-Reimer commented on plugins/vdr-softhdcuvid/PKGBUILD
> +  make clean
I didn't expect the build system of softhdcuvid to be that bad. At some point the author suggested exactly what I'm doing here
https://www.vdr-portal.de/forum/index.php?thread/133411-softhdcuvid-bauen-f%C3%BCr-maintainer-nun-mit-ffnvcodec/&postID=1323580#post1323580

Probably the best way would be then to create three copies of the source code on top of "build" to have one individual copy for each plugin. Then build them all in "build()".

2021-05-16 14:53 UTC, M-Reimer commented on plugins/vdr-live/PKGBUILD
> +  git init --quiet && git apply --verbose "${srcdir}/8.patch"
Probably it would have been best to leave this out until the pull request is accepted. Usually on Arch no "foreign" patches are applied. If you really need this (especially as I'm not using "Live" at all and probably there are not many vdr4arch users anyway, so you may be one of the last users needing this) then feel free to keep it this way. But it has to be removed if the pull request is denied at some point.

2021-05-16 14:58 UTC, M-Reimer commented on plugins/vdr-softhdcuvid/PKGBUILD
> +  make clean
Seems like Arch does such stuff in "prepare()": https://github.com/archlinux/svntogit-packages/blob/packages/glibc/trunk/PKGBUILD#L42-L43
But I couldn't find an example where the complete source code needs to be copied.

2021-05-16 16:34 UTC, tmn505 commented on plugins/vdr-softhdcuvid/PKGBUILD
> +  make clean
I saw such construct in some split packages, where actual build was done in package().
I also did such thing on top of my changes and it also builds fine, the only redundant compilation is building translations, everything else is done once:

````
diff --git a/plugins/vdr-softhdcuvid/PKGBUILD b/plugins/vdr-softhdcuvid/PKGBUILD
index bf2d7edee275..8c307bdb0e88 100644
--- a/plugins/vdr-softhdcuvid/PKGBUILD
+++ b/plugins/vdr-softhdcuvid/PKGBUILD
@@ -27,6 +27,19 @@ prepare() {
 
   # Disable OSS. Arch Linux doesn't ship OSS
   sed -i '/OSS /d' Makefile
+
+  # Don't clean built plugin binary
+  sed -i 's/\*\.so//' Makefile
+}
+
+build() {
+  cd "${srcdir}/vdr-plugin-${_plugname}"
+  make CUVID=1
+  make clean
+  make VAAPI=1
+  make clean
+  make DRM=1 LIBPLACEBO=0
+  make clean
 }
 
 package_vdr-softhdcuvid() {
@@ -35,8 +48,8 @@ package_vdr-softhdcuvid() {
   backup=("etc/vdr/conf.avail/50-$_plugname.conf")
 
   cd "${srcdir}/vdr-plugin-${_plugname}"
-  make clean
-  make CUVID=1 DESTDIR="${pkgdir}" install
+  install -Dm755 "lib${pkgname}.so" "${pkgdir}$(pkg-config --variable=libdir vdr)/lib${pkgname}.so.$(pkg-config --variable=apiversion vdr)"
+  make CUVID=1 DESTDIR="${pkgdir}" install-i18n
 
   install -Dm644 "$srcdir/50-$_plugname.conf" "$pkgdir/etc/vdr/conf.avail/50-softhdcuvid.conf"
 }
@@ -47,8 +60,8 @@ package_vdr-softhdvaapi() {
   backup=("etc/vdr/conf.avail/50-softhdvaapi.conf")
 
   cd "${srcdir}/vdr-plugin-${_plugname}"
-  make clean
-  make VAAPI=1 DESTDIR="${pkgdir}" install
+  install -Dm755 "lib${pkgname}.so" "${pkgdir}$(pkg-config --variable=libdir vdr)/lib${pkgname}.so.$(pkg-config --variable=apiversion vdr)"
+  make VAAPI=1 DESTDIR="${pkgdir}" install-i18n
 
   install -Dm644 "$srcdir/50-$_plugname.conf" "$pkgdir/etc/vdr/conf.avail/50-softhdvaapi.conf"
   sed -i 's/softhdcuvid/softhdvaapi/' "$pkgdir/etc/vdr/conf.avail/50-softhdvaapi.conf"
@@ -60,8 +73,8 @@ package_vdr-softhddrm() {
   backup=("etc/vdr/conf.avail/50-softhddrm.conf")
 
   cd "${srcdir}/vdr-plugin-${_plugname}"
-  make clean
-  make DRM=1 LIBPLACEBO=0 DESTDIR="${pkgdir}" install
+  install -Dm755 "lib${pkgname}.so" "${pkgdir}$(pkg-config --variable=libdir vdr)/lib${pkgname}.so.$(pkg-config --variable=apiversion vdr)"
+  make DRM=1 LIBPLACEBO=0 DESTDIR="${pkgdir}" install-i18n
 
   install -Dm644 "$srcdir/50-$_plugname.conf" "$pkgdir/etc/vdr/conf.avail/50-softhddrm.conf"
   sed -i 's/softhdcuvid/softhddrm/' "$pkgdir/etc/vdr/conf.avail/50-softhddrm.conf"

````

2021-05-16 16:50 UTC, tmn505 commented on plugins/vdr-live/PKGBUILD
> +  git init --quiet && git apply --verbose "${srcdir}/8.patch"
Ok, I'll leave this change out and wait for PR to be merged and new version taged. I'm using my own fork with some modifications, so it won't hurt me.

2021-05-17 19:14 UTC, M-Reimer commented on plugins/vdr-softhdcuvid/PKGBUILD
> +  make clean
Seems to be a good solution to me

2021-05-18 15:00 UTC, merged

2021-05-18 15:00 UTC, M-Reimer commented
Merging now. Won't build as VDR itself fails building.

2021-05-18 15:18 UTC, tmn505 commented
Which is strange, it built first push of this PR, maybe some upstream package caused this? Will need to check logs.

2021-05-18 15:24 UTC, tmn505 commented
It's the gcc update to 11 which is causing this.

2021-05-18 15:46 UTC, M-Reimer commented
Yes, it is. And I also have an idea how to fix it but probably I won't have time until tomorrow.

Thanks anyway for your pull request with all the updates. Great to see someone still caring about vdr4arch.